import type { MarginProps } from '../types'

export function getMarginClass({
  m,
  mSm,
  mMd,
  mLg,
  mXl,
  mXxl,
  mX,
  mXSm,
  mXMd,
  mXLg,
  mXXl,
  mXXxl,
  mY,
  mYSm,
  mYMd,
  mYLg,
  mYXl,
  mYXxl,
  mB,
  mBSm,
  mBMd,
  mBLg,
  mBXl,
  mBXxl,
  mT,
  mTSm,
  mTMd,
  mTLg,
  mTXl,
  mTXxl,
  mS,
  mSSm,
  mSMd,
  mSLg,
  mSXl,
  mSXxl,
  mE,
  mESm,
  mEMd,
  mELg,
  mEXl,
  mEXxl,
}: MarginProps) {
  return {
    [`m-${m}`]: m,
    [`m-sm-${mSm}`]: mSm,
    [`m-md-${mMd}`]: mMd,
    [`m-lg-${mLg}`]: mLg,
    [`m-xl-${mXl}`]: mXl,
    [`m-xxl-${mXxl}`]: mXxl,
    [`mx-${mX}`]: mX,
    [`mx-sm-${mXSm}`]: mXSm,
    [`mx-md-${mXMd}`]: mXMd,
    [`mx-lg-${mXLg}`]: mXLg,
    [`mx-xl-${mXXl}`]: mXXl,
    [`mx-xxl-${mXXxl}`]: mXXxl,
    [`my-${mY}`]: mY,
    [`my-sm-${mYSm}`]: mYSm,
    [`my-md-${mYMd}`]: mYMd,
    [`my-lg-${mYLg}`]: mYLg,
    [`my-xl-${mYXl}`]: mYXl,
    [`my-xxl-${mYXxl}`]: mYXxl,
    [`mb-${mB}`]: mB,
    [`mb-sm-${mBSm}`]: mBSm,
    [`mb-md-${mBMd}`]: mBMd,
    [`mb-lg-${mBLg}`]: mBLg,
    [`mb-xl-${mBXl}`]: mBXl,
    [`mb-xxl-${mBXxl}`]: mBXxl,
    [`mt-${mT}`]: mT,
    [`mt-sm-${mTSm}`]: mTSm,
    [`mt-md-${mTMd}`]: mTMd,
    [`mt-lg-${mTLg}`]: mTLg,
    [`mt-xl-${mTXl}`]: mTXl,
    [`mt-xxl-${mTXxl}`]: mTXxl,
    [`ms-${mS}`]: mS,
    [`ms-sm-${mSSm}`]: mSSm,
    [`ms-md-${mSMd}`]: mSMd,
    [`ms-lg-${mSLg}`]: mSLg,
    [`ms-xl-${mSXl}`]: mSXl,
    [`ms-xxl-${mSXxl}`]: mSXxl,
    [`me-${mE}`]: mE,
    [`me-sm-${mESm}`]: mESm,
    [`me-md-${mEMd}`]: mEMd,
    [`me-lg-${mELg}`]: mELg,
    [`me-xl-${mEXl}`]: mEXl,
    [`me-xxl-${mEXxl}`]: mEXxl,
  }
}
