import type { PaddingProps } from '../types'

export function getPaddingClass({
  p,
  pSm,
  pMd,
  pLg,
  pXl,
  pXxl,
  pX,
  pXSm,
  pXMd,
  pXLg,
  pXXl,
  pXXxl,
  pY,
  pYSm,
  pYMd,
  pYLg,
  pYXl,
  pYXxl,
  pB,
  pBSm,
  pBMd,
  pBLg,
  pBXl,
  pBXxl,
  pT,
  pTSm,
  pTMd,
  pTLg,
  pTXl,
  pTXxl,
  pS,
  pSSm,
  pSMd,
  pSLg,
  pSXl,
  pSXxl,
  pE,
  pESm,
  pEMd,
  pELg,
  pEXl,
  pEXxl,
}: PaddingProps) {
  return {
    [`p-${p}`]: p,
    [`p-sm-${pSm}`]: pSm,
    [`p-md-${pMd}`]: pMd,
    [`p-lg-${pLg}`]: pLg,
    [`p-xl-${pXl}`]: pXl,
    [`p-xxl-${pXxl}`]: pXxl,
    [`px-${pX}`]: pX,
    [`px-sm-${pXSm}`]: pXSm,
    [`px-md-${pXMd}`]: pXMd,
    [`px-lg-${pXLg}`]: pXLg,
    [`px-xl-${pXXl}`]: pXXl,
    [`px-xxl-${pXXxl}`]: pXXxl,
    [`py-${pY}`]: pY,
    [`py-sm-${pYSm}`]: pYSm,
    [`py-md-${pYMd}`]: pYMd,
    [`py-lg-${pYLg}`]: pYLg,
    [`py-xl-${pYXl}`]: pYXl,
    [`py-xxl-${pYXxl}`]: pYXxl,
    [`pb-${pB}`]: pB,
    [`pb-sm-${pBSm}`]: pBSm,
    [`pb-md-${pBMd}`]: pBMd,
    [`pb-lg-${pBLg}`]: pBLg,
    [`pb-xl-${pBXl}`]: pBXl,
    [`pb-xxl-${pBXxl}`]: pBXxl,
    [`pt-${pT}`]: pT,
    [`pt-sm-${pTSm}`]: pTSm,
    [`pt-md-${pTMd}`]: pTMd,
    [`pt-lg-${pTLg}`]: pTLg,
    [`pt-xl-${pTXl}`]: pTXl,
    [`pt-xxl-${pTXxl}`]: pTXxl,
    [`ps-${pS}`]: pS,
    [`ps-sm-${pSSm}`]: pSSm,
    [`ps-md-${pSMd}`]: pSMd,
    [`ps-lg-${pSLg}`]: pSLg,
    [`ps-xl-${pSXl}`]: pSXl,
    [`ps-xxl-${pSXxl}`]: pSXxl,
    [`pe-${pE}`]: pE,
    [`pe-sm-${pESm}`]: pESm,
    [`pe-md-${pEMd}`]: pEMd,
    [`pe-lg-${pELg}`]: pELg,
    [`pe-xl-${pEXl}`]: pEXl,
    [`pe-xxl-${pEXxl}`]: pEXxl,
  }
}
